require_relative 'env'
require_relative 'lib/check_search'

Logging.logger.root.level = :info
Logging.logger.root.add_appenders(Logging.appenders.stdout)

desc "Downloads checks to run from Google Docs"
task :download_checks do
  require 'time'
  require 'open-uri'
  require 'fileutils'

  # Link generated by going to:
  #   File
  #     Publish to the web
  #       Get a link to the published data
  #          then choose CSV
  resource_id = "0AmD7K4ab1dYrdDR5c2tITTNHRUZqajFTTU8wODAzZ1E"
  io = open("https://docs.google.com/spreadsheet/pub?key=#{resource_id}&single=true&gid=0&output=csv")

  file = File.new("downloaded-weighted-search-terms-#{Time.now.utc.iso8601}.csv", "wb")
  file.write(io.read)
  file.close

  # Create a symlink called "weighted-search-terms.csv" pointing at the file just downloaded
  FileUtils.ln_s(File.basename(file), "weighted-search-terms.csv", force: true)
end

desc "Runs search health check using weighted check data"
task :check_search do
  if ENV["CREDENTIALS"]
    authentication = ENV["CREDENTIALS"].split(":")
  else
    authentication = nil
  end

  search_host = ENV["SEARCH_BASE"] || "http://search.dev.gov.uk"

  slow = !ENV["SLOW"].nil?

  filename = "weighted-search-terms.csv"
  test_search = CheckSearch.new(authentication, search_host, filename, slow)
  test_search.call
end

require 'rake/testtask'
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

task :default => :test
